In [2]:
import torch
a = torch.tensor([[1,2,3], [4,5,6]], requires_grad=True, dtype=torch.float)
b = a + 2
c = 2 * b * b
out = c.mean()
out.backward()
print(a.grad)

tensor([[2.0000, 2.6667, 3.3333],
        [4.0000, 4.6667, 5.3333]])


In [2]:
out.backward()
print(a.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [3]:
print(c)

tensor([[ 18.,  32.,  50.],
        [ 72.,  98., 128.]], grad_fn=<MulBackward0>)


In [4]:
print(out)

tensor(66.3333, grad_fn=<MeanBackward0>)


In [7]:
print(a.requires_grad)
with torch.no_grad():
    print((a**2).requires_grad)
print(a.requires_grad)

True
False
True


In [9]:
# stop tracking operation
a.detach()
print(a.requires_grad)
print(a.detach().requires_grad)

True
False


In [10]:
# do .backward twice using retain_graph param with True
a = torch.ones((2,3), requires_grad=True)
b = a + 2
c = 2 * b * b
out = c.mean()
out.backward(retain_graph=True)
print(a.grad)
out.backward()
print(a.grad)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
